

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorNone)
#pragma config(Sensor, S3,     light,          sensorNone)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorF,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


void topHatDrive ();
void buttonControl();
void moveHanger(int dir);

task main()
{
	waitForStart();
	wait1Msec(1000);


	while(true)
	{
		getJoystickSettings(joystick);

		topHatDrive();											//check for top hat presses

		buttonControl();										//check for button presses

  }
}

void buttonControl()
{

	  getJoystickSettings(joystick);

		if(joy2Btn(1)==1)
	  {


		}


		//flag control routine
		if(joy2Btn(2)==1)
		{
			motor[motorI]=100;

		}
		else
	  {
	  	motor[motorI]=0;}
	 // if(joy2Btn(3)==1)
		//{
		//	motor[motorA]=-100;
		//	motor[motorB]=-100;

	 // }

		//Panel up
	  //if (joy2Btn(7)==1)
	  //{
			//servo[servo3] = 90;
			//servo [servo4] = 90;
			//wait1Msec(1000);
	  //}
	  //else
	  //{
	  //	servo[servo3]=0;
	  //	servo[servo4]=0;
	  //		  }


	  //Panel down
	  if (joy2Btn(1 )==1)
	  {
	  	motor[motorJ] = 100;
	  	//servo[servo4] = 120;
	  	//servo[servo4] = 0;
	  //	wait1Msec(1000);
	  }
	  else
	  {
	  	motor[motorJ] = 0;
	  	//servo[servo4] = 180;
	  }
if (joy2Btn(6)==1)
	  {
	  	servo[servo2] = 10;
	  	//servo[servo4] = 120;
	  	//servo[servo4] = 0;
	  //	wait1Msec(1000);
	  }
	  else
	  {
	  	servo[servo2] = 240;
	  	//servo[servo4] = 180;
	  }



	  //lift control routine
	  if(joy2Btn(5)==1)
	  {
	  	//	moveHanger(1); //lift up
	  		motor[motorH]=-100;
		}
	  else if(joy2Btn(4)==1)
	  {
	  		motor[motorH]=100;
	  		//moveHanger(0); //lift down
		}
		else
		{
			motor[motorH]=0;
		}

}



void topHatDrive()
{

  getJoystickSettings(joystick);

	if(joystick.joy1_TopHat==0)
  {
  	motor[motorD]= -100;
  	motor[motorE]= -100;
  }//forward
	else if(joystick.joy1_TopHat==1)
	{
  	motor[motorD]= -100; 								//left
  	motor[motorE]= -20; 								//right
  }//forward right


 else if(joystick.joy1_TopHat==7)
	{
  	motor[motorD]= -20;
  	motor[motorE]= -100;
  }//forward left
	else if(joystick.joy1_TopHat==4)
	{
  	motor[motorD]= 100;
  	motor[motorE]= 100;
  }//backward
  else if(joystick.joy1_TopHat==3)
	{
  	motor[motorD]= 20;
  	motor[motorE]= 100;
  }//backward right
	else if(joystick.joy1_TopHat==5)
  {
  	motor[motorD]= 100;
  	motor[motorE]= 20;
  }//backward left
  else if (joy1Btn(5)==1)
	{
  	 motor[motorD]= 100; 								//left
  	 motor[motorE]= -100; 								//right
  }
  else if (joy1Btn(6)==1)
  {
     motor[motorD]= -100; 								//left
   	 motor[motorE]= 100; 								//right
  }
  else
  {
	  motor[motorD]= 0;
  	motor[motorE]= 0;
	}


}


void moveHanger(int dir)
{
	if (dir == 1)
	{
		//raise up hanging device
		motor[motorH]=-100;
	}
	else if (dir == 0)
	{
		//lower hanging device
		motor[motorH]=100;
	}
}
